name: bagua-net ci

on:
  push:
    branches: [ master-ci ]
  pull_request:
    branches: [ master-ci ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Unit Test
      run: cd rust/bagua-net/cc && make test
