on:
  push:
    branches:
      - master-ci
  pull_request:
    branches:
      - master-ci

name: Rustfmt

jobs:
  format:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt
            override: true
      - name: rustfmt bagua-core
        run: |
          cd rust/bagua-core && cargo + fmt -- --check
      - name: rustfmt bagua-net
        run: |
          cd rust/bagua-net && cargo + fmt -- --check
